### ISSUE TITLE
ai + human bot team cooperation

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#53]
Not sure if it's issue but when I play team games, the bots seem to try and actively bomb each other. Even in 1 vs 7 Skynet mode. I think they should act more as a team and work to sabotage their opponents instead of friendly fire.

**Comment by SimpleTease** [comment]
Tested more. They're just sloppy around each other or roam around in large groups sometimes, instead of fanning out or attacking in zones.

But cpu will target humans in sex team play. I get constantly tagged by friendly cpu bots who should be on my team.

**Comment by SimpleTease** [comment]
And bot can get overconfident when allowed to drop 3+ bombs. Several times during 1v1 or 1v2, the cpu killed itself or its partner because it didn't bother to check safety limits and just happily dropped bombs every chance, got trapped and flamed.

**Comment by frranck** [comment]
Yes they do care about the countdown time, otherwise they wouldn't be able to walk next to their own bomb. 
Here is the fitness function on where to drop a bomb: 
https://github.com/Javanaise/mrboom-libretro/blob/master/ai/GridFunctions.cpp#L661 
They also do care about teams but they could also decide to kill you if it's a good team strategy:
https://github.com/Javanaise/mrboom-libretro/blob/master/ai//MrboomHelper.cpp#L512 
IMO If AI feels too systematic it's not going to be fun to play, it needs to do random shit like humans...

**Comment by SimpleTease** [comment]
`They also do care about teams but they could also decide to kill you if it's a good team strategy:`

It was just 2 girls in the bottom-right corner with the other having a kangaroo, and the enemy males far elsewhere locked behind some barriers. The team friendly goober kept dropping bombs anytime I got near but ignored the other girls. They got me pretty mad. :rofl: 

`IMO If AI feels too systematic it's not going to be fun to play, it needs to do random shit like humans...`

Experimentally verified. Spent hours fooling around with in-gameplay combos and enjoyed it all-around. Now I'm going to do netplay and start hammering the world! 😸 

I'm satisfied to close this now.

**Comment by SimpleTease** [comment]
Took me some time to understand the friendly bot behavior. If there's `nothing` to bomb (no enemies, walls, misc stuff) then they won't drop a bomb near you. Otherwise they will drop it figuring that you'll get out of the way, and they won't mind sacrificing you if the team gains something. They can get very aggressive when opponents are around. :rofl:
