### ISSUE TITLE
make disease more fun?

### ISSUE THREAD

**Issue by SimpleTease** [Javanaise/mrboom-libretro#66]
The sickness you get is fun to suffer through, but you have to intentionally infect yourself with it. No bots will do it and most humans won't either.

I was wondering if maybe the gameplay could be changed to make it more usable?
- Have it affect 1 random player, instead of person who picks it up.
- Have a few mystery bonus icons that hide what the powerup is. If unlucky, you got the diseased one.

I think either idea would make it more valuable for bots and players alike. With some added danger and new strategy.

**Comment by frranck** [comment]
there is still a bunch of use cases:
- players that don't know about them
- when you really want to go somewhere or need to run away
- if you self contaminate in order to infect a stronger player and go for a draw
That's part of the minimalistic gameplay which I liked in early versions (i.e. Dynablaster) that made the game more skill focused versus some more "random shit is happening" elements (that I associate with the SNES versions)

**Comment by SimpleTease** [comment]
> if you self contaminate in order to infect a stronger player and go for a draw

Didn't know that was possible. :)

> That's part of the minimalistic gameplay which I liked in early versions (i.e. Dynablaster) that made the game more skills focused versus some more "random shit is happening" elements (that I associate with the SNES versions)

I do see the appeal of the non-randomness.
